import Head from 'next/head'
import fs from 'fs/promises'
import path from 'path'
import dynamic from 'next/dynamic';

const NoSSRForceGraph = dynamic(() => import('../lib/NoSSRForceGraph'), {
  ssr: false
});

import { HeartIcon, FireIcon, LightningBoltIcon, EmojiHappyIcon, CameraIcon} from '@heroicons/react/solid'
import SmallCard from '../components/Cards/SmallCard'
import Maps from '../components/Maps'
import ForceGraphLinks from '../components/ForceGraphLinks'

const myData = {
  nodes: [{ id: 'a' }, { id: 'b' }, { id: 'c' }],
  links: [
    { source: 'a', target: 'b' },
    { source: 'c', target: 'a' }
  ]
};

export default function Home(props) {
  const {members, villages, fgraph} = props
  // console.log('Members 1: ', fgraph)
  // console.log('Villages', villages)
  return (
    <div className='container mx-4 p-4'>
      <Head>
        <title>Iyengars 1000+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='lg:flex block'>
        <div className="p-2">
          <h2 className='h2'>Welcome to Iyengars, 1000+ </h2> 
          <div className="md:text-md lg:text-xl">
            <p className="mt-2">A growing compendium of Iyengars, including non-Iyengars, and non-Indians married or born to an Iyengar. 
                We cover: 
            </p>
            <div className="px-5 mt-2">
              <p>&rarr; 8+ generations from 1700 AD</p>
              <p>&rarr; Immortalize funny, fascinating, amazing, endearing, and inspiring memories</p>
              <p>&rarr; Individal details</p>
              <p>&rarr; Tagged memory and photo stories</p>
              <p>&rarr; Clans of 5+ generations </p>
              <p>&rarr; Search connections between any 2 people</p>
            </div>
          </div>
        </div>
        <div className="xs:min-w-[300px] h-[400px] md:min-w-[600px] lg:min-w-[1000px]">
          <Maps villages={villages}/>
        </div>
      </section>

      <section className="pt-4">
        <h2 className="h2">Cherished Memories from 1900's</h2> 
        <div className="grid grid-cols-1 md:grid-cols-2 m-2">
          <div>
            <div className="flex space-x-2 text-lg text-semibold">
                <HeartIcon className='h-6 text-red-300 cursor-pointer'/>
                <p className="text-red-300">Romance and intrigue</p>
              </div>
              <p className="px-4 text-sm">&rarr; 1918: VKSwamy: @18 years went surreptiously to the neighboring village to check out bethorthed</p>
              <p className="px-4 text-sm">&rarr; 1954: Lilly, in a high pitched voice </p>
              <div className="flex space-x-2 text-lg text-semibold mt-2">
                <FireIcon className='h-6 text-blue-500 text-semibold cursor-pointer'/>
                <p className="text-blue-600">Courage</p>
              </div>
              <p className="px-4 text-sm">&rarr; 1905: Despite threat of ostacrization, Mr. K went to study at St. Joseph Boys School</p>
              <p className="px-4 text-sm">&rarr; 1958: Veda Seshadri scaled 15 feet wall to save neighbor</p>
              <div className="flex space-x-2 text-lg text-semibold mt-2">
                <LightningBoltIcon className='h-6 text-orange-500 cursor-pointer'/>
                <p className="text-orange-500 text-semibold">Inspiration</p>
              </div>
              <p className="px-4 text-sm">&rarr; 1855: Sampat Iyengar found the iron ores at Kudhremukh</p>
              <div className="flex space-x-2 text-lg text-semibold mt-2">
                <EmojiHappyIcon className='h-6 text-green-600 cursor-pointer'/>
                <p className="text-green-600 text-semibold">Happy and funny</p>
              </div>
                <p className="px-4 text-sm">&rarr; 1925: Veppodu Krishnaswamy set post-office roof on fire with cracker</p>
                <p className="px-4 text-sm">&rarr; 2001: Desikan tried to get 1000 rape whistles when his daughter went to college</p>
              <div className="flex space-x-2 text-lg text-semibold mt-2">
                <CameraIcon className='h-6 text-red-500 cursor-pointer'/>
                <p className="text-red-500 text-semibold">Awards and Recognitions</p>
              </div>
          </div>

          <div className='grid grid-cols-2 md:grid-cols-3lg:grid-cols-4
              xl:grid-cols-3'>
              {
                members?.map(m=>(
                  <SmallCard key={m.id}
                    name={m.id}
                    imageURL={m.imageURL}
                  />
                ))
              }
          </div>
        </div>
      </section>

       {/* <section className="mt-4">
        <h2 className="h2">Connections</h2>
        <NoSSRForceGraph graphData={myData} height={200}/>
       
      </section>  */}
      {/* <div className = "grid grid-cols-1 md:grid-cols-2">
        <NoSSRForceGraph graphData={myData} />
        </div> */}
    </div>
  )
}

export async function getStaticProps(){
  const filePath = path.join(process.cwd(), 'data', 'sample.json')
  const jsonData = await fs.readFile(filePath)
  const data = JSON.parse(jsonData)

  const filePathv = path.join(process.cwd(), 'data', 'villages.json')
  const jsonDatav = await fs.readFile(filePathv)
  const datav = JSON.parse(jsonDatav)

  const filePathl = path.join(process.cwd(), 'data', 'AshaNicky.json')
  const jsonDatal = await fs.readFile(filePathl)
  const datal = JSON.parse(jsonDatal)
  // console.log('Villages : ', datal)

  return {
    props: {
      members: data.members,
      villages: datav.villages,
      fgraph: datal
    }
  }
}
